"""Desk Brief: rules-based morning readout from the app's own official series. Every sentence is
generated by an explicit rule in analytics/desk_brief.py with the numbers inline. Not a forecast."""

from datetime import datetime

import pandas as pd
import streamlit as st

import assumptions as A
from analytics import desk_brief as B
from ui.brief_html import LABEL, brief_html
from ui.common import TABLE_ROW_PX, explain, table
from ui.macro_loader import get
from ui.series_chart import NEWLINE

st.info(f"**{LABEL.upper()}.** Every sentence below is produced by a fixed rule from the numbers "
        "it quotes. It describes where official series sit against their own history; it says "
        "nothing about what happens next.")

c1, c2 = st.columns([3, 2])
looks = list(A.BRIEF_LOOKBACK_MONTHS)
lookback = c1.radio("History for z-scores and percentiles", looks,
                    index=looks.index(A.BRIEF_DEFAULT_LOOKBACK), horizontal=True, key="db_lookback")
printable = c2.toggle("Printable one-page view", value=False, key="db_print")
months = A.BRIEF_LOOKBACK_MONTHS[lookback]
start = None if months is None else pd.Timestamp.today().normalize() - pd.DateOffset(months=months)

loaded, errors = get(B.all_deps())
data = {k: s.data for k, s in loaded.items()}
rows, skipped = B.build_rows(data, start)
cached = [s for s in loaded.values() if s.status == "cached"]
if errors:
    st.warning(f"{len(errors)} source(s) failed with no cached copy; series that need them are "
               "listed under 'Not available' below.")
if cached:
    st.warning("Live fetch failed, cached copy used for: " + "; ".join(
        f"{s.spec.name} (fetched {s.fetched_at[:16].replace('T', ' ')})" for s in cached) + ".")
if rows.empty:
    st.error("No series could be loaded, so there is no brief. " + " ".join(errors))
    st.stop()

generated = datetime.now().strftime("%d %b %Y %H:%M")
lookback_text = (f"{lookback} (from {start:%d %b %Y})" if start is not None else
                 "Max (each series' full history)")
funding = B.funding_sentences(data)
top = B.movers(rows)
mover_lines = [B.mover_sentence(r) for r in top.to_dict("records")]
stretched_rows = rows[(rows["Level status"] == "stretched") | (rows["Move status"] == "stretched")]
stretched = [B.row_sentence(r) for r in stretched_rows.to_dict("records")]
sources = [f"{s.spec.name}: {s.spec.source}, {s.spec.frequency}, as of {s.as_of:%d %b %Y} "
           f"({s.status})" for s in loaded.values()]

# Display and export table: numbers kept numeric for CSV, formatted for the page
export = rows.drop(columns="key").copy()
export["As of"] = export["As of"].astype(str)
export["From"] = export["From"].astype(str)
compact = [{"Series": r["Series"], "Freq": r["Frequency"][0].upper(), "As of": r["As of"],
            "Last": B._num(r["Last"], r["Unit"]), "Chg": B._chg(r["Change"], r["Change unit"]),
            "Chg z": f"{r['Change z']:+.2f}", "Lvl z": f"{r['Level z']:+.2f}",
            "Pctile": f"{r['Percentile']:.0f}", "Status": (
                "STRETCHED" if "stretched" in (r["Level status"], r["Move status"]) else "normal")}
           for r in export.to_dict("records")]
html = brief_html("Desk Brief", generated, lookback_text, funding, mover_lines, stretched, compact,
                  skipped, sources)

d1, d2 = st.columns(2)
d1.download_button("Export to CSV", export.to_csv(index=False).encode("utf-8"),
                   file_name=f"desk_brief_{datetime.now():%Y%m%d}.csv", mime="text/csv",
                   key="db_csv")
d2.download_button("Download printable page (HTML)", html.encode("utf-8"),
                   file_name=f"desk_brief_{datetime.now():%Y%m%d}.html", mime="text/html",
                   key="db_html")

if printable:
    st.caption("Printable view: white page for printing. Use the browser's Print (Ctrl+P), or "
               "download the HTML above and print that.")
    st.html(html)
    st.stop()

st.caption(f"Generated {generated}. History window: {lookback_text}. Changes are "
           "observation-to-observation at each series' own frequency (day, week or month); no "
           "daily statistic is computed for weekly or monthly data.")

st.subheader("Funding conditions")
st.caption(f"Latest value against the last observation at least {A.BRIEF_COMPARE_DAYS} calendar "
           "days earlier; monthly series against the previous month.")
st.markdown(NEWLINE.join(f"- {s}" for s in funding) if funding else "No funding series loaded.")

st.subheader("Largest movers")
st.caption(f"Top {A.BRIEF_TOP_MOVERS} by the absolute z-score of the latest change against that "
           "series' own changes over the history window.")
st.markdown(NEWLINE.join(f"{i}. {s}" for i, s in enumerate(mover_lines, start=1)))

st.subheader(f"Stretched: beyond {A.BRIEF_STRETCH_Z:g} SD")
if stretched:
    st.markdown(NEWLINE.join(f"- {s}" for s in stretched))
else:
    st.markdown(f"No series has a level or latest change beyond {A.BRIEF_STRETCH_Z:g} SD of its "
                "history window.")

st.subheader("All series")
compact_df = pd.DataFrame(compact)
for group in dict.fromkeys(rows["Group"]):
    st.markdown(f"**{group}**")
    part = compact_df[(rows["Group"] == group).to_numpy()]
    table(part, height=(len(part) + 1) * TABLE_ROW_PX + 3)  # every row visible, no inner scroll
with st.expander("Every series as a sentence"):
    st.markdown(NEWLINE.join(f"- {B.row_sentence(r)}" for r in rows.to_dict("records")))
if skipped:
    with st.expander(f"Not available ({len(skipped)})"):
        st.markdown(NEWLINE.join(f"- {s}" for s in skipped))
with st.expander("Sources (series, provider, frequency, as of, live or cached)"):
    st.markdown(NEWLINE.join(f"- {s}" for s in sources))
explain("the brief's rules", f"""
- **Level z** = (latest level − mean) / SD over the history window; **Pctile** = share of
  observations at or below the latest level.
- **Chg** = latest observation-to-observation change; **Chg z** = (latest change − mean change) /
  SD of changes over the window. Yields are in %, their changes in bp.
- **Stretched** = |z| > {A.BRIEF_STRETCH_Z:g} (level or change); otherwise normal.
- **Largest movers** = ranked by |Chg z|.
- **Funding conditions** compare with the last observation on or before {A.BRIEF_COMPARE_DAYS} days
  earlier. Direction words come from the sign of the change.
- Spreads and slopes use only dates where both inputs are published (nothing is filled).
""")
